[package]
name = "png-viewer"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.10.0", features = ["canvas", "image"] }
native-dialog = "0.7.0"
rand = "0.8.5"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[build-dependencies]
winres = "0.1"