[package]
name = "png-viewer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version = "0.10.0", features = ["canvas", "image"] }
native-dialog = "0.7.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
